### PR TITLE
All stories editable by every user #32-(Updation in user auth)

### PR DESCRIPTION
**Pull request by manasgoel2002**
#32 added user authentication to the story-fetching

### CODE REVIEW

**Review by saineshnakra — CHANGES_REQUESTED** [review]
Looks good but one issue
I am getting this error when I add a story and I am lead back to home: 
Cannot update a component (`HotReload`) while rendering a different component (`HomePage`). To locate the bad setState() call inside `HomePage`, follow the stack trace as described in https://react.dev/link/setstate-in-render
error @ intercept-console-error.js:56
intercept-console-error.js:56 Each child in a list should have a unique "key" prop.

Check the render method of `HomePage`. See https://react.dev/link/warning-keys for more information.

**Review by pankajLaunchX — COMMENTED** [review]
Is the edit story feature working? For me, the story is not getting updated and it is throwing a 401 error.

**Comment by saineshnakra** [comment]
> Is the edit story feature working? For me, the story is not getting updated and it is throwing a 401 error.

unauthorized error. need to fix the api for editing stories (put request would be there or post check it out)

**Review by saineshnakra — APPROVED** [review]
looks good

**Pull request merged**
