### PR TITLE
feat: #1 Add Story

### PR DESCRIPTION
**Pull request by Ramshankar07**

### CODE REVIEW

**Comment by Ramshankar07** [comment]
### 1)API Route (POST handler):
- Added better error handling with nested try-catch blocks
- Improved input validation for the story parameter
- Added proper user authentication checking with Auth0 ID and username headers

### 2) New File `src/app/api/story/[id]/route.ts` 
- Helps to identify multiple stories of single user by checking the authentication
- Also added validations for updation of stories also in `src/app/api/story/route.ts`

### 3) New File `src/app/notes/add/page.tsx`
- Reuses components in StoryInput to modify or add story

### 4)  New File `src/app/notes/page.tsx`
- UI for managing multiple stories by displaying title and date
- Added validation when no strories added

### 5) Modification in `src/components/StoryInput.tsx`
- redirectpath which helps to reuse it in `src/app/notes/add/page.tsx`

**Comment by 1geek0** [comment]
@Ramshankar07 the build is failing. Check before pushing by using `npm run build`

**Comment by Ramshankar07** [comment]
I think it is good now @manasgoel2002, can you pull this and verify it for me? I'll add the changes in the comments now

**Comment by Ramshankar07** [comment]
There is still an error in retreiving the personal story! I'm doing it

**Comment by 1geek0** [comment]
The UI should look like this
image

**Comment by 1geek0** [comment]
@manasgoel2002 Invalid date
image

**Review by 1geek0 — APPROVED** [review]
lgtm

**Pull request merged**
