### PR TITLE
#3 placeholder text in storyinput.tsx

### PR DESCRIPTION
**Pull request by Ramshankar07**

### CODE REVIEW

**Review by 1geek0 — COMMENTED** [review]
@Ramshankar07 Don't use it as it is. Adapt it along something like "Be as descriptive as possible, here's some examples of thing you could say"

**Comment by Ramshankar07** [comment]
Ohh okay i got it

**Comment by 1geek0** [comment]
I'm merging this for now. But we'll need to change this soon

**Review by 1geek0 — APPROVED** [review]
This needs to change. But I'm passing it for now

**Pull request merged**
