### PR TITLE
Sync airtable resources to mongodb #10

### PR DESCRIPTION
**Pull request by manasgoel2002**
This Python script integrates Airtable, MongoDB, and OpenAI APIs to fetch, process, and store records with embeddings. It is designed for use in a healthcare or resource management context, enabling efficient indexing and retrieval of data.

### CODE REVIEW

**Comment by 1geek0** [comment]
@manasgoel2002 have you tested this on local db?

**Comment by manasgoel2002** [comment]
I have not tested it in the local database, but I ran the code once and
downloaded data from the hosted database. It looks good to me.

**Comment by 1geek0** [comment]
Okay. Can we put the data in ‘test’ database? There’s some other db on the
same server being used right now

**Comment by manasgoel2002** [comment]
@1geek0 You Want me to do this 
`mongo_db = mongo_client["medical_resources"]`.      ----->.      `mongo_db = mongo_client["test"]`

**Review by Ramshankar07 — APPROVED** [review]

**Pull request merged**
