### PR TITLE
Demo mode #11

### LINKED ISSUE #11: Demo mode
Fill in the story box with a sample meningioma story on Screen 1

### PR DESCRIPTION
**Pull request by Ramshankar07**
fixes #11

### CODE REVIEW

**Comment by 1geek0** [comment]
@Ramshankar07 fill in the text only upon clicking a button. This is for us when testing. The real user would be confused by a pre-filled story

**Review by 1geek0 — CHANGES_REQUESTED** [review]
@Ramshankar07  fill in the text only upon clicking a button. This is for us when testing. The real user would be confused by a pre-filled story

**Comment by 1geek0** [comment]
not working

**Comment by Ramshankar07** [comment]
@1geek0 Can you check it now

**Comment by pankajLaunchX** [comment]
Hey @1geek0  i have added demo datas for stories and timeline. I have changed the prefill story button to a demo mode button. This would prevent unnecessary api calls which are not required in demo mode. please review it and let me know of any changes. 

Also the /home and /notes probably require some specific cookies for authentication and hence the demo doesnot work if the user hasn't tried signing in. Please let me know of any solution for the same.

**Comment by pankajLaunchX** [comment]
Hey @1geek0 . Can you give a feedback on the demo mode added.

**Review by saineshnakra — COMMENTED** [review]
Major repo, let's connect on call before we merge

**Comment by pankajLaunchX** [comment]
Hey. Do i need to be part of the meet ?

**Comment by pankajLaunchX** [comment]
> > Hey. Do i need to be part of the meet ?
> 
> Let's keep a 20-30 minute call tomorrow just reviewing the 3 issues and their fixes before we merge to prod.

Sure.

**Review by saineshnakra — COMMENTED** [review]
When can we have a call?

**Comment by pankajLaunchX** [comment]
@saineshnakra could you review this now?

**Review by saineshnakra — APPROVED** [review]
Looks good to me

**Review by saineshnakra — APPROVED** [review]
Changes seem fine now

**Review by saineshnakra — APPROVED** [review]
.

**Pull request merged**
